#!/usr/bin/env bash
#
# Boot a throwaway imvault, seeded with sample media, so you can look at a
# populated instance without registering anything by hand.
#
# Nothing here touches your real ./data directory: it wipes and uses
# ./demo-data instead (gitignored), which `make clean-demo` removes.
#
#   make demo
#   PORT=9000 make demo
#
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

PORT="${PORT:-8080}"
DATA_DIR="${DATA_DIR:-$PWD/demo-data}"
BASE="http://127.0.0.1:$PORT"
USERNAME="${USERNAME:-demo}"
PASSWORD="${PASSWORD:-demo-password}"
ALBUM="demo-album"

JAR="$(mktemp)"
WORK="$(mktemp -d)"
BINARY="$WORK/imvault"
SERVER_PID=""

cleanup() {
  if [[ -n "$SERVER_PID" ]]; then
    kill "$SERVER_PID" 2>/dev/null || true
    wait "$SERVER_PID" 2>/dev/null || true
  fi
  rm -f "$JAR"
  rm -rf "$WORK"
}
trap cleanup EXIT INT TERM

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v go >/dev/null 2>&1 || die "go is not on PATH"

# Do not stomp on something already listening.
if curl -fsS -o /dev/null "$BASE/healthz" 2>/dev/null; then
  die "something is already serving $BASE; try PORT=9000 make demo"
fi

say "Resetting the demo data directory ($DATA_DIR)"
rm -rf "$DATA_DIR"

say "Building imvault"
go build -o "$BINARY" ./cmd/imvault

say "Starting the server on $BASE"
IMVAULT_ADDR="127.0.0.1:$PORT" \
IMVAULT_DATA_DIR="$DATA_DIR" \
IMVAULT_BASE_URL="$BASE" \
IMVAULT_LOG_LEVEL=warn \
  "$BINARY" &
SERVER_PID=$!

for _ in $(seq 1 50); do
  curl -fsS -o /dev/null "$BASE/healthz" 2>/dev/null && break
  sleep 0.2
done
curl -fsS -o /dev/null "$BASE/healthz" 2>/dev/null || die "the server did not start"

csrf() { awk '/imvault_csrf/ {print $7}' "$JAR" | tail -1; }

say "Creating the demo account ($USERNAME / $PASSWORD)"
curl -sS -c "$JAR" -b "$JAR" -o /dev/null "$BASE/"
curl -sS -c "$JAR" -b "$JAR" -o /dev/null -X POST "$BASE/register" \
  -d "csrf_token=$(csrf)" \
  -d "username=$USERNAME" \
  -d "password=$PASSWORD"

say "Minting an API key"
curl -sS -c "$JAR" -b "$JAR" -o "$WORK/panel.html" -X POST "$BASE/settings/api-keys" \
  -H 'HX-Request: true' -d "csrf_token=$(csrf)" -d "name=local demo"
API_KEY="$(grep -o 'value="imv_[A-Za-z0-9]*_[A-Za-z0-9]*"' "$WORK/panel.html" | head -1 | sed 's/value="//;s/"//')"
[[ -n "$API_KEY" ]] || die "could not mint an API key"

say "Generating sample media"
mkdir -p "$WORK/media"
go run ./scripts/genmedia -dir "$WORK/media"

# A clip makes the video path visible, but it is entirely optional.
if command -v ffmpeg >/dev/null 2>&1; then
  if ffmpeg -hide_banner -loglevel error \
      -f lavfi -i "testsrc=size=480x360:rate=15" -t 3 \
      -c:v libvpx -pix_fmt yuv420p -y "$WORK/media/clip.webm" 2>/dev/null; then
    printf '  %s\n' "$WORK/media/clip.webm"
  else
    warn "ffmpeg could not encode a sample clip; skipping it"
  fi
else
  warn "ffmpeg not found; skipping the sample clip (clips would get a placeholder poster)"
fi

say "Uploading through the API"
curl -sS -o /dev/null -X POST "$BASE/api/v1/albums" \
  -H "Authorization: Bearer $API_KEY" -H 'Content-Type: application/json' \
  -d '{"title":"Demo album","description":"Sample media generated by make demo","visibility":"public"}'

FIRST_ID=""
for file in "$WORK"/media/*; do
  response="$(curl -sS -X POST "$BASE/api/v1/upload" \
    -H "Authorization: Bearer $API_KEY" \
    -F "files=@$file" -F "visibility=public" -F "album=$ALBUM")"

  id="$(printf '%s' "$response" | grep -o '"id": "[a-z0-9]*"' | head -1 | sed 's/.*: "//;s/"//')"
  if [[ -z "$id" ]]; then
    warn "upload of $(basename "$file") failed: $(printf '%s' "$response" | head -c 200)"
    continue
  fi
  [[ -n "$FIRST_ID" ]] || FIRST_ID="$id"
done

# A couple of tags, so the tag index and per-tag pages have content.
if [[ -n "$FIRST_ID" ]]; then
  for tag in "landscape" "demo"; do
    curl -sS -o /dev/null -X POST "$BASE/api/v1/files/$FIRST_ID/tags" \
      -H "Authorization: Bearer $API_KEY" -H 'Content-Type: application/json' \
      -d "{\"name\":\"$tag\"}"
  done
fi

bold() { printf '\033[1m%s\033[0m' "$*"; }

printf '\n  %s\n\n' "$(bold 'imvault is running')"
printf '    %-14s %s\n' \
  'Open'     "$BASE" \
  'Gallery'  "$BASE/gallery" \
  'Albums'   "$BASE/albums" \
  'Tags'     "$BASE/tags" \
  'API keys' "$BASE/settings/api-keys" \
  'Sign in'  "$USERNAME / $PASSWORD" \
  'API key'  "$API_KEY"
printf '\n  Sample content was uploaded through the API, exactly as a script would.\n'
printf '  Data lives in %s; "make clean-demo" removes it.\n' "$DATA_DIR"
printf '\n  Press Ctrl-C to stop.\n\n'

wait "$SERVER_PID"
